apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  apiServerAddress:
  podSubnet: "10.245.1.0/16"
  serviceSubnet: "10.246.1.0/16"
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: JoinConfiguration
    metadata:
      name: config
    nodeRegistration:
      kubeletExtraArgs:
        cgroup-root: "/kubelet"
  - |
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: InitConfiguration
    metadata:
      name: config
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"    
        cgroup-root: "/kubelet"
  kubeadmConfigPatchesJSON6902:
